"""Dependency-free browser application for live checkpoint previews."""

# ruff: noqa: E501 -- The dependency-free HTML application is embedded below.

from http.server import SimpleHTTPRequestHandler

INDEX_HTML = r"""<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ReSnake 检查点独立评估</title>
<style>
:root{color-scheme:light;--ink:#17212b;--muted:#66717d;--line:#d8dee5;--blue:#176b9b;--green:#20825b;--orange:#db792a;--paper:#fff;--wash:#f5f7f9}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:15px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif}
header{border-bottom:1px solid var(--line);padding:20px 28px;display:flex;align-items:end;justify-content:space-between;gap:20px}h1{font-size:23px;margin:0;font-weight:650}h2{font-size:15px;margin:0 0 10px}p{margin:4px 0}.muted{color:var(--muted);font-size:13px}.live{font-variant-numeric:tabular-nums;color:var(--green)}
main{display:grid;grid-template-columns:minmax(480px,1fr) 390px;gap:0;max-width:1320px;margin:auto;border-left:1px solid var(--line);border-right:1px solid var(--line)}
.viewer{padding:24px;border-right:1px solid var(--line)}.stage{background:#fff;border:1px solid #aeb8c2;min-height:420px;display:grid;place-items:center;overflow:hidden}canvas{display:block;width:100%;height:100%;min-height:420px}
.facts{display:grid;grid-template-columns:repeat(5,minmax(80px,1fr));border:1px solid var(--line);border-top:0}.fact{padding:10px 12px;border-right:1px solid var(--line)}.fact:last-child{border-right:0}.fact b{display:block;font-size:18px;font-variant-numeric:tabular-nums}.fact span{font-size:12px;color:var(--muted)}
.controls{display:flex;align-items:center;gap:8px;margin-top:12px;flex-wrap:wrap}.controls button,.controls select,.segments button{border:1px solid #aeb8c2;background:#fff;color:var(--ink);border-radius:2px;padding:6px 10px;cursor:pointer}.controls button:hover,.controls select:hover,.segments button:hover{border-color:var(--blue)}
aside{padding:0}.aside-head{padding:20px;border-bottom:1px solid var(--line)}.segments{list-style:none;padding:0;margin:0}.segments li{border-bottom:1px solid var(--line);padding:12px 16px;display:grid;grid-template-columns:1fr auto;gap:8px;cursor:pointer}.segments li:hover{background:var(--wash)}.segments li.active{border-left:3px solid var(--blue);padding-left:13px;background:#f4f9fc}.segments strong{font-weight:600}.segments small{display:block;color:var(--muted);margin-top:2px}.tag{font-size:12px;color:var(--blue);font-variant-numeric:tabular-nums}
.event-head{display:flex;justify-content:space-between;align-items:baseline;padding:16px;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.event-head h2{margin:0}.events{list-style:none;padding:0;margin:0;max-height:360px;overflow:auto}.events li{border-bottom:1px solid var(--line);padding:9px 16px;cursor:pointer}.events li:hover{background:var(--wash)}.events time{display:inline-block;min-width:58px;color:var(--blue);font:12px ui-monospace,monospace}.events strong{font-size:13px}.events small{display:block;margin-left:58px;color:var(--muted)}
.details{border-top:1px solid var(--line);margin-top:20px;padding-top:14px;display:grid;grid-template-columns:1fr 1fr;gap:8px 20px}.details code{font-size:12px;color:#364453;overflow-wrap:anywhere}.warning{border-left:3px solid var(--orange);padding:8px 10px;margin-top:14px;background:#fffaf4;color:#5d4938;font-size:13px}
@media(max-width:850px){main{display:block;border:0}.viewer{border-right:0;padding:14px}.stage,canvas{min-height:310px}.facts{grid-template-columns:repeat(2,1fr)}.fact{border-bottom:1px solid var(--line)}header{padding:16px}.details{grid-template-columns:1fr}}
</style></head><body>
<header><div><h1>ReSnake 检查点独立评估</h1><p class="muted">问题：在固定评估协议与同一初始随机流（seed）下，最近 N 个 checkpoint 的确定性闭环完整单局行为如何演化？</p></div><div id="service" class="live">正在连接…</div></header>
<main><section class="viewer"><div class="stage"><canvas id="board"></canvas></div>
<div class="facts"><div class="fact"><b id="update">—</b><span>checkpoint update</span></div><div class="fact"><b id="score">—</b><span>当前食物数</span></div><div class="fact"><b id="tick">—</b><span>本局逻辑 tick</span></div><div class="fact"><b id="age">—</b><span>所属决策</span></div><div class="fact"><b id="mode">—</b><span>动作选择</span></div></div>
<div class="controls"><button id="pause">暂停</button><button id="newest">跳到最新</button><button id="next-clip">下一段</button><button id="episode-end">跳到本局结尾</button><label class="muted">速度 <select id="speed"><option value="auto" selected>自适应（约90秒/局）</option><option value="1">1×</option><option value="10">10×</option><option value="100">100×</option><option value="1000">1000×</option></select></label><span id="position" class="muted"></span></div>
<div class="details"><div><span class="muted">策略文件</span><br><code id="checkpoint">—</code></div><div><span class="muted">固定评估 seed</span><br><code id="seed">—</code></div><div><span class="muted">内部 policy version</span><br><code id="policy-version">—</code></div><div><span class="muted">协议指纹</span><br><code id="protocol">—</code></div><div><span class="muted">实际手柄</span><br><code id="gamepad">—</code></div><div><span class="muted">本局结果</span><br><code id="outcome">—</code></div></div>
<div class="warning">这是保存权重在新建仿真中的受控评估，不是训练当时采集的轨迹，也不代表多 seed 泛化成绩。同一 seed 只固定初始随机流；策略改变蛇身和空格后，后续食物与障碍仍可分叉。每段只含一局，从 reset 播放到死亡、胜利或正式时间截断。</div></section>
<aside><div class="aside-head"><h2>最近 <span id="retention">N</span> 个 checkpoint</h2><p class="muted">同一 seed、确定性动作、每个 checkpoint 一局；旧版本自动过期。</p></div><ol id="segments" class="segments"></ol><div class="event-head"><h2>随播放出现的事件</h2><span id="event-count" class="muted">0 / 0</span></div><ol id="events" class="events"></ol></aside></main>
<script>
const canvas=document.getElementById('board'),ctx=canvas.getContext('2d');let manifest=null,trace=null,current=null,currentFrame=null,frameIndex=0,frameProgress=0,lastTime=performance.now(),paused=false,loading=false,frameLoading=false,loadToken=0,frameRequest=0,refreshRequest=0,refreshTimer=null,eventCursor=0,lastEventTick=-1,chunkCache=new Map();
const $=id=>document.getElementById(id);function esc(s){return String(s??'—')}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(r.width*d));canvas.height=Math.max(1,Math.round(r.height*d));draw()}addEventListener('resize',resize);
function outcome(reason,won,truncated){if(won)return'通关（棋盘填满）';if(truncated||reason==='time_limit')return'达到评估上限（删失）';return({wall_collision:'撞墙',self_collision:'撞到自身',obstacle_collision:'撞到障碍'}[reason]||reason||'未知结局')}
function draw(){ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);if(!trace||!currentFrame)return;const f=currentFrame,pad=18*(devicePixelRatio||1),cw=(canvas.width-2*pad)/f.width,ch=(canvas.height-2*pad)/f.height,c=Math.max(2,Math.min(cw,ch)),ox=(canvas.width-c*f.width)/2,oy=(canvas.height-c*f.height)/2;
 ctx.fillStyle='#fafbfc';ctx.fillRect(ox,oy,c*f.width,c*f.height);ctx.strokeStyle='#e3e7eb';ctx.lineWidth=1;for(let x=0;x<=f.width;x++){ctx.beginPath();ctx.moveTo(ox+x*c,oy);ctx.lineTo(ox+x*c,oy+f.height*c);ctx.stroke()}for(let y=0;y<=f.height;y++){ctx.beginPath();ctx.moveTo(ox,oy+y*c);ctx.lineTo(ox+f.width*c,oy+y*c);ctx.stroke()}
 const cell=(p,color)=>{if(!p)return;ctx.fillStyle=color;ctx.fillRect(ox+p[0]*c+1,oy+p[1]*c+1,Math.max(1,c-2),Math.max(1,c-2))};for(const p of f.obstacles)cell(p,'#89939e');for(const p of f.pending_obstacles)cell(p,'#e7b34d');for(let i=f.snake.length-1;i>=0;i--)cell(f.snake[i],i?'#72b9d8':'#176b9b');cell(f.food,'#e56b45');
 $('update').textContent=trace.source_update;$('score').textContent=f.score;$('tick').textContent=f.episode_tick+'/'+trace.episode_ticks;$('age').textContent=f.decision;$('mode').textContent=trace.mode==='stochastic'?'采样':'确定性';$('checkpoint').textContent=trace.checkpoint;$('seed').textContent=trace.seed;$('policy-version').textContent=trace.policy_version;$('protocol').textContent=trace.evaluation_protocol_sha256.slice(0,16);$('gamepad').textContent=formatPad(f.actual_report);$('outcome').textContent=`${outcome(trace.termination,trace.won,trace.truncated)} · ${trace.final_score} 个食物`;$('position').textContent=`第 ${frameIndex+1}/${trace.frame_count} 个游戏帧 · 第 ${currentIndex()+1}/${manifest?.clips.length||0} 个 checkpoint`;updateEvents(f.episode_tick)}
function formatPad(a){if(!a)return'—';const names=['↑','↓','←','→','Start','Back','LS','RS','LB','RB','A','B','X','Y','LX','LY','RX','RY','LT','RT'];return a.map((v,i)=>Math.abs(v)>.05?`${names[i]} ${Number(v).toFixed(2)}`:'').filter(Boolean).join(' · ')||'neutral'}
const eventNames={game_start:'游戏开始',food_eaten:'吃到食物',obstacle_announced:'障碍已生成并预告',obstacle_applied:'障碍正式生效',obstacle_rejected:'障碍被拒绝',game_end:'游戏结束'};
function eventDetail(e){if(e.type==='game_start')return`seed ${e.seed} · ${e.width}×${e.height}`;if(e.type==='food_eaten')return`分数 ${e.score} · D=${e.distance} · T=${e.ticks_since_previous_food} tick · 奖励 ${Number(e.reward).toFixed(3)}`;if(e.type==='obstacle_announced')return`${(e.cells||[]).length} 格 · 计划在游戏 tick ${e.activate_game_tick} 生效`;if(e.type==='obstacle_applied')return`${(e.cells||[]).length} 格 · ${e.reason}`;if(e.type==='obstacle_rejected')return`${(e.cells||[]).length} 格 · ${e.reason}`;if(e.type==='game_end')return`${outcome(e.reason,e.won,e.truncated)} · 最终 ${e.score} 个食物`;return''}
function resetEvents(){eventCursor=0;lastEventTick=-1;$('events').replaceChildren();$('event-count').textContent=`0 / ${trace?.events?.length||0}`}
function appendEvent(e){const li=document.createElement('li'),line=document.createElement('div'),time=document.createElement('time'),name=document.createElement('strong'),detail=document.createElement('small');time.textContent=`tick ${e.episode_tick}`;name.textContent=eventNames[e.type]||e.type;detail.textContent=eventDetail(e);line.append(time,name);li.append(line,detail);li.onclick=()=>{frameProgress=0;lastTime=performance.now();resetEvents();seek(Math.max(0,Math.min(e.frame_index,trace.frame_count-1)))};$('events').append(li)}
function updateEvents(tick){if(!trace)return;if(tick<lastEventTick)resetEvents();while(eventCursor<trace.events.length&&trace.events[eventCursor].episode_tick<=tick){appendEvent(trace.events[eventCursor++])}$('event-count').textContent=`${eventCursor} / ${trace.events.length}`;if(tick!==lastEventTick)$('events').scrollTop=$('events').scrollHeight;lastEventTick=tick}
function applyDelta(state,d){const n={...state,...d};delete n.head_added;delete n.tail_removed;if(Object.hasOwn(d,'snake'))n.snake=d.snake;else if(d.head_added){n.snake=[d.head_added,...state.snake];if(d.tail_removed)n.snake.pop()}return n}
async function chunkFrames(desc,token){if(chunkCache.has(desc.url))return chunkCache.get(desc.url);const r=await fetch(desc.url,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const data=await r.json();if(token!==loadToken)throw Error('stale load');let state=data.initial,frames=[state];for(const delta of data.deltas){state=applyDelta(state,delta);frames.push(state)}chunkCache.set(desc.url,frames);while(chunkCache.size>2)chunkCache.delete(chunkCache.keys().next().value);return frames}
async function seek(index,fail=false){if(!trace||frameLoading)return;const token=loadToken,request=++frameRequest,desc=trace.chunks.find(c=>index>=c.start_frame&&index<=c.end_frame);if(!desc)return;frameLoading=true;try{const frames=await chunkFrames(desc,token);if(token!==loadToken||request!==frameRequest)return;frameIndex=index;currentFrame=frames[index-desc.start_frame];draw()}catch(e){if(token===loadToken&&request===frameRequest)$('service').textContent='回放分块已过期，刷新列表';if(fail)throw e}finally{if(request===frameRequest)frameLoading=false}}
function currentIndex(){return Math.max(0,(manifest?.clips||[]).findIndex(x=>x.id===current))}async function play(id){const clip=(manifest?.clips||[]).find(x=>x.id===id);if(!clip)return;const token=++loadToken;++frameRequest;frameLoading=false;loading=true;chunkCache.clear();currentFrame=null;try{const r=await fetch(clip.url,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const value=await r.json();if(token!==loadToken)return;trace=value;current=id;frameIndex=0;frameProgress=0;lastTime=performance.now();resetEvents();renderList();await seek(0,true)}catch(e){if(token===loadToken){current=null;trace=null;currentFrame=null;$('service').textContent='回放已过期，刷新列表';scheduleRefresh(500)}}finally{if(token===loadToken)loading=false}}
function next(){if(!manifest?.clips.length||loading)return;const i=currentIndex();play(manifest.clips[(i+1)%manifest.clips.length].id)}function newest(){if(manifest?.clips.length)play(manifest.clips.at(-1).id)}
function playbackSpeed(){const value=$('speed').value;if(value==='auto')return trace?Math.max(1,trace.episode_ticks/(trace.logic_fps*90)):1;return Math.max(1,Number(value)||1)}
function animate(now){const elapsed=Math.min(.25,(now-lastTime)/1000);lastTime=now;if(!paused&&!document.hidden&&trace&&currentFrame&&!frameLoading){frameProgress+=elapsed*trace.logic_fps*playbackSpeed();if(frameProgress>=1){const advance=Math.floor(frameProgress);frameProgress-=advance;if(frameIndex+1>=trace.frame_count){frameProgress=0;next()}else seek(Math.min(trace.frame_count-1,frameIndex+advance))}}requestAnimationFrame(animate)}
function renderList(){const list=$('segments');list.replaceChildren();for(const c of [...(manifest?.clips||[])].reverse()){const li=document.createElement('li');if(c.id===current)li.className='active';const left=document.createElement('div'),title=document.createElement('strong'),small=document.createElement('small'),right=document.createElement('span');title.textContent=`update ${c.source_update}`;small.textContent=`${c.mode==='stochastic'?'采样':'确定性'} · seed ${c.seed} · ${outcome(c.termination,c.won,c.truncated)} · ${c.final_score} 食物`;left.append(title,small);right.className='tag';right.textContent=`${c.episode_ticks} tick`;li.append(left,right);li.onclick=()=>play(c.id);list.append(li)}}
function bytes(v){if(v<1024)return`${v} B`;if(v<1048576)return`${(v/1024).toFixed(1)} KiB`;return`${(v/1048576).toFixed(1)} MiB`}
function scheduleRefresh(delay=3000){clearTimeout(refreshTimer);if(!document.hidden)refreshTimer=setTimeout(refresh,delay)}
async function refresh(){const request=++refreshRequest;clearTimeout(refreshTimer);try{const r=await fetch('manifest.json',{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const value=await r.json();if(request!==refreshRequest)return;const oldLatest=manifest?.latest;manifest=value;$('retention').textContent=value.retention;$('service').textContent=value.status==='ready'?`在线 · 最新快照 update ${value.training_update??value.latest_update??'—'} · ${bytes(value.storage_bytes??0)}`:`${value.status} · ${value.message??''}`;renderList();if(value.latest&&(!current||value.latest!==oldLatest))play(value.latest);else if(current&&!value.clips.some(x=>x.id===current))newest()}catch(e){if(request===refreshRequest)$('service').textContent='连接中断，正在重试'}finally{if(request===refreshRequest)scheduleRefresh()}}
$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'继续':'暂停'};$('newest').onclick=newest;$('next-clip').onclick=next;$('episode-end').onclick=()=>{if(trace){paused=true;$('pause').textContent='继续';frameProgress=0;seek(trace.frame_count-1)}};$('speed').onchange=()=>{frameProgress=0;lastTime=performance.now()};document.addEventListener('visibilitychange',()=>{lastTime=performance.now();clearTimeout(refreshTimer);if(!document.hidden)refresh()});resize();refresh();requestAnimationFrame(animate);
</script></body></html>"""


class NoStoreHandler(SimpleHTTPRequestHandler):
    """Serve preview assets without browser or proxy caching."""

    def end_headers(self):
        self.send_header(
            "Cache-Control", "no-store, no-cache, must-revalidate, max-age=0"
        )
        self.send_header("Pragma", "no-cache")
        self.send_header("Expires", "0")
        self.send_header("X-Content-Type-Options", "nosniff")
        super().end_headers()

    def log_message(self, _format, *_args):
        return
