"""Compatibility entrypoint for the legacy-v0 deterministic video recorder."""

from resnake_gym_legacy.v0.record_video import (
    DEFAULT_CELL_SIZE,
    DEFAULT_DENSE_END_TICKS,
    DEFAULT_DENSE_START_TICKS,
    DEFAULT_FPS,
    DEFAULT_HEIGHT,
    DEFAULT_MAX_LOGIC_STEPS,
    DEFAULT_MIDDLE_FRAMES,
    DEFAULT_SEED,
    DEFAULT_WIDTH,
    ActionFunction,
    FfmpegInfo,
    FrameFunction,
    FrameSchedule,
    Outcome,
    _decode_stderr,
    _encode_second_pass,
    _ffmpeg_command,
    _ffmpeg_version,
    _find_ffmpeg,
    _format_fps,
    _load_action_function,
    _nonnegative_int,
    _oracle_initial_options,
    _positive_float,
    _positive_int,
    _resolve_model_path,
    _rollout,
    _sha256_file,
    _stop_encoder,
    _update_trajectory_digest,
    _write_json_atomic,
    build_parser,
    build_schedule,
    main,
    record_video,
)

__all__ = [
    "DEFAULT_CELL_SIZE",
    "DEFAULT_DENSE_END_TICKS",
    "DEFAULT_DENSE_START_TICKS",
    "DEFAULT_FPS",
    "DEFAULT_HEIGHT",
    "DEFAULT_MAX_LOGIC_STEPS",
    "DEFAULT_MIDDLE_FRAMES",
    "DEFAULT_SEED",
    "DEFAULT_WIDTH",
    "ActionFunction",
    "FfmpegInfo",
    "FrameFunction",
    "FrameSchedule",
    "Outcome",
    "_decode_stderr",
    "_encode_second_pass",
    "_ffmpeg_command",
    "_ffmpeg_version",
    "_find_ffmpeg",
    "_format_fps",
    "_load_action_function",
    "_nonnegative_int",
    "_oracle_initial_options",
    "_positive_float",
    "_positive_int",
    "_resolve_model_path",
    "_rollout",
    "_sha256_file",
    "_stop_encoder",
    "_update_trajectory_digest",
    "_write_json_atomic",
    "build_parser",
    "build_schedule",
    "main",
    "record_video",
]


if __name__ == "__main__":
    raise SystemExit(main())
